### ISSUE TITLE
Similar project

### ISSUE THREAD

**Issue by mitchellwrosen** [rbros/stdlib.hs#6]
Just FYI, I have a similar effort on Hackage: https://hackage.haskell.org/package/planet-mitchell

Feel free to steal ideas, or whatever :)

**Comment by creichert** [comment]
Awesome! Yours is much more comprehensive than this one. I already have
some ideas just looking through it.

Our project is really minimal, we just use it across our internal
projects. We've wanted to create a web-specific opinionated prelude
(uuid, http-types, wai, http-client, microlens?).

Anyways, thanks!

**Comment by mitchellwrosen** [comment]
Of course! A web stdlib sounds very useful :) I'll close this issue out.
